### ISSUE TITLE
JsonLogic.Net 1.1.6 - NuGet Gallery

### ISSUE THREAD

**Issue by lrushl** [yavuztor/JsonLogic.Net#10]
There is already 1.1.6 version at NuGet Gallery but no code changes in GitHub repo/changelog etc.

Could you please clarify on this.

**Comment by yavuztor** [comment]
The builds are not automated. I must have forgotten to push my code to origin. See this commit: https://github.com/yavuztor/JsonLogic.Net/commit/1727f3a34dbdb3bc63e420ae4ea58a6d7a525eb5
