### ISSUE TITLE
System.NullReferenceException error when calling JsonLogicEvaluator.Apply

### ISSUE THREAD

**Issue by SaviChinnadurai** [yavuztor/JsonLogic.Net#12]
I am getting below error while calling JsonLogicEvaluator.Apply function:

Error:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=JsonLogic.Net
  StackTrace:
   at JsonLogic.Net.EvaluateOperators.<>c__DisplayClass12_1.<DoubleArgsSatisfy>b__1(JToken a)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at JsonLogic.Net.EvaluateOperators.<>c__DisplayClass12_0.<DoubleArgsSatisfy>b__0(IProcessJsonLogic p, JToken[] args, Object data)
   at JsonLogic.Net.JsonLogicEvaluator.Apply(JToken rule, Object data)
   at JsonLogicConsole.Program.Main(String[] args) in C:\Code\Sandbox\JsonLogicDemo\JsonLogicConsole\Program.cs:line 33

Code: 
using JsonLogic.Net;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;

namespace JsonLogicConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            // The data that the rule will run against. 
            object data = getEntity();

            // Rule definition retrieved as JSON text
            string jsonText = "{\">\": [{\"var\": \"Eventid\"}, 3]}";

            // Parse json into hierarchical structure
            var rule = JObject.Parse(jsonText);

            // Create an evaluator with default operators.
            var evaluator = new JsonLogicEvaluator(EvaluateOperators.Default);

            // Apply the rule to the data.  - Error Thrown here
            var result = evaluator.Apply(rule, data);
        }

        static Event getEntity()
        {
            return new Event
            {
                Eventid = 10,
                Hires = new List<Hire>()
                {
                    new Hire{ ReservationStatus=""  }
                }
            };
        }
    }

    public class Event
    {
        public int Eventid;
        public List<Hire> Hires;
    }
	
    public class Hire
    {
        public string ReservationStatus;
    }
}

**Comment by yavuztor** [comment]
I think the issue is in the var operator,

`string jsonText = "{\">\": [{\"var\": \"Eventid\"}, 3]}"`
should be 
`string jsonText = "{\">\": [{\"var\": [\"Eventid\"]}, 3]}";`

However, I see that the exception message doesn't help very much. I will focus on improving the exceptions in next release.
