### ISSUE TITLE
var not being recognized in array 'in' operator.

### ISSUE THREAD

**Issue by richbog** [yavuztor/JsonLogic.Net#2]
The rule and Data below return false in .Net, but returns true in JavaScript.
{"in":[{"var":"marital_status"},["Single","Married","Divorced","Widowed","Separated"]]}
Data: {"marital_status": "Divorced"}

This rule returns true in both .Net and JavaScript
{"in":["Divorced",["Single","Married","Divorced","Widowed","Separated"]]}

The {"var":"marital_status"} doesn't seem to be getting replaced with the Data in the .Net version.

**Comment by yavuztor** [comment]
When I entered the above into json tests, it returned true as it is supposed to.

This must be an issue with the `var` operator itself. It first checks whether data is array, dictionary-like, or IEnumerable. If none of those, it will try to use reflection to get the referenced value. I will need to see how you have the data object in your c# code, to be able to diagnose the issue. Can you please send the code you used to test?

**Comment by yavuztor** [comment]
Found the issue to be the equality check inside the "in" operator. The check was relying on Object.Equals method instead of type-agnostic equality. Resolved the issue and pushed version 1.1.3 to nuget.org.
