### ISSUE TITLE
It appears that putting an "and" condition in a "filter" does not work

### ISSUE THREAD

**Issue by stephenweaver** [yavuztor/JsonLogic.Net#3]
Hey, not sure if you're still doing work on this. It's a neat idea, and I was a little disappointed that http://jsonlogic.com doesn't have a C# implementation, so checked yours out.

I ran into an issue with rules that look like this. Oddly enough, if i just remove part 2 of the "and" condition, it works as expected. 
```
{
  "filter": [
    { "var": "" },
    {
      "and": [
        {
          ">=": [
            { "var": "Prop1.PropA" },
           1
          ]
        },
        {
          ">=": [
            { "var": "Prop2.PropB" },
            19
          ]
        }
      ]
    }
  ]
}

```
with data that looks like this

```
[
  {
    "Prop1": {
      "PropA": 5
    },
    "Prop2": {
      "PropB": 18
    }
  },
  {
    "Prop1": {
      "PropA": 1
    },
    "Prop2": {
      "PropB": 35
    }
  }
]
```

Any ideas?

Cheers,
Stephen

**Comment by stephenweaver** [comment]
Turns out if I 
```
var stringData = JsonConvert.SerializeObject(dataObject);
var data = JsonConvert.DeserializeObject(stringData);
```
and then just use `data`, all is well. \shrug

**Comment by yavuztor** [comment]
Hi @stephenweaver, thanks for reporting this issue.  I will add a unit test for that to see why it needs a round-trip on json serialization. Meanwhile, if you have any code fixes/changes, please make a pull request.

**Comment by yavuztor** [comment]
@stephenweaver, I added a new test with your input. It seems to pass the test. You can check it out and update the test, if your setup was different. Please make a pull request if you can replicate the issue with the test.
