### ISSUE TITLE
[Suggestion] Downgrade Newtonsoft json version for dependent projects

### ISSUE THREAD

**Issue by SergAtGitHub** [yavuztor/JsonLogic.Net#5]
Hi @yavuztor ,

You have a good implementation of jsonlogic manifest and my team wants to use it in our project, but the problem is that our project has a dependency on Newtonsoft.Json of version 9.0.1.

Can you please make the project to be dependent on Newtonsoft.Json of lower version?
Thanks.

**Comment by yavuztor** [comment]
@SergAtGithub,

I will take a look at this soon. I don't think it would be a problem. It might take a day or two.  Meanwhile you can use assembly redirection to get it built in your project.

**Comment by yavuztor** [comment]
@SergAtGitHub, I published the new version of the library with Newtonsoft.Json dependency adjusted. v1.1.5 also has corrections on some operations.
